Repository mjgwon24/dgu-semi-erp-front, pull requests merged in 2025-03, with the labels that each got.

#61 Feature/schedule bankbook modal
  src/components/common/modals/AddBankbook/AddBankbookPresenter.jsx
  src/components/common/modals/AddSchedule/AddSchedulePresenter.jsx
Labels: fix

#68 feat & fix: 예산보고서 모달 ui 구현 및 상태 추가
  src/components/common/modals/BudgetReport/BudgetReportModal.js
  src/components/units/budgetReport/BudgetReport.container.jsx
  src/components/units/budgetReport/BudgetReport.presenter.jsx
Labels: feature, fix

#70 feat: 알림페이지 UI 구현
  pages/notify/index.jsx
  src/components/common/layout/header/index.jsx
  src/components/common/layout/sidebar/index.jsx
  src/components/common/layout/table/pagination.jsx
  src/components/units/notify/Notify.container.jsx
  src/components/units/notify/Notify.presenter.jsx
Labels: feature

#67 feature: myPage UI 구현
  pages/myPage/index.jsx
  src/components/units/myPage/myPage.container.jsx
  src/components/units/myPage/myPage.presenter.jsx
Labels: feature

#72 update: 공통 layout ui 반영
  pages/_app.js
  pages/_document.js
  src/components/common/layout/sidebar/index.jsx
  src/components/units/generalSchedule/GeneralSchedule.presenter.jsx
  src/components/units/notify/Notify.presenter.jsx
Labels: feature

#76 update: EditableTable 현재 페이지 상태 prop로 전달 및 빈 테이블 표시 높이 변경
  src/components/common/layout/table/editableTable/index.jsx
  src/components/common/layout/table/tableWrapper/index.jsx
Labels: update

#77 update: 통장관리 페이지 테이블 가로로 늘어나는 버그 수정, 변경된 EditableTable 컴포넌트 반영
  src/components/units/bankbookManagement/bankbookManagement.container.jsx
  src/components/units/bankbookManagement/bankbookManagement.presenter.jsx
Labels: update
