Repository mjgwon24/dgu-semi-erp-front, pull requests merged in 2025-02, with the labels that each got.

#3 feat: 조회조건 영역 컴포넌트 구현 (1차)
  src/components/common/layout/conditions/conditionItem/index.jsx
  src/components/common/layout/conditions/conditionPanel/index.jsx
  src/components/common/layout/conditions/conditionPicker/index.jsx
  src/components/common/layout/conditions/conditionbar/index.jsx
Labels: feature

#8 feat: 조회 결과 테이블 영역 컴포넌트 구현 (1차)
  next.config.mjs
  package.json
  src/components/common/layout/table/editableTable/index.jsx
  src/components/common/layout/table/index.jsx
  src/components/common/layout/table/tableCell/index.jsx
  src/components/common/layout/table/tableHeader/index.jsx
  src/components/common/layout/table/tableRow/index.jsx
  src/components/common/layout/table/tableTitle/index.jsx
  src/components/common/layout/table/tableWrapper/index.jsx
Labels: feature

#15 6 feature sidebar component
  src/components/common/layout/sidebar/index.jsx
Labels: feature

#14 7 feature headerlayout
  package-lock.json
  package.json
  pages/_app.js
  pages/member/peopleManagement.jsx
  redux/slices/memberSlice.js
  redux/slices/uiSlice.js
  redux/slices/userSlice.js
  redux/store.js
  src/components/common/layout/header/index.jsx
  src/components/member/MemberDetail.jsx
  src/components/member/MemberForm.jsx
  src/components/member/MemberList.jsx
  tailwind.config.js
Labels: feature

#19 feat: 예산계획 페이지 구현
  pages/budgetPlan/index.jsx
  src/components/units/budgetPlan/BudgetPlan.container.jsx
  src/components/units/budgetPlan/BudgetPlan.presenter.jsx
  tailwind.config.js
Labels: feature

#23 Update: package.json 콤마(,) 누락 개선
  package.json
Labels: update

#24 fix: layout에 존재하는 Header, Sidebar 중복 선언으로 인한 UI 중복 노출 제거
  src/components/units/budgetPlan/BudgetPlan.container.jsx
  src/components/units/budgetPlan/BudgetPlan.presenter.jsx
Labels: fix

#30 update: 조회결과 테이블 영역 EditableTable 컴포넌트 개선
  src/components/common/layout/table/editableTable/index.jsx
  src/components/common/layout/table/tableRow/index.jsx
Labels: update

#32 feat: 예산 보고서 페이지 UI 구현
  pages/budgetReport/index.jsx
  src/components/units/budgetReport/BudgetReport.container.jsx
  src/components/units/budgetReport/BudgetReport.presenter.jsx
Labels: feature

#35 feat: 통장관리 페이지 UI 구현
  pages/bankbookManagement/index.jsx
  src/components/units/bankbookManagement/bankbookManagement.container.jsx
  src/components/units/bankbookManagement/bankbookManagement.presenter.jsx
Labels: feature

#39 feat: sidebar 및 header 아이콘 및 텍스트 크기조정
  pages/_app.js
  src/components/common/layout/header/index.jsx
  src/components/common/layout/sidebar/index.jsx
  tailwind.config.js
Labels: fix

#37 feat: schedule 추가 모달 추가
  src/components/common/modals/AddBankbook.jsx
  src/components/common/modals/AddBankbook/AddBankbookContainer.jsx
  src/components/common/modals/AddBankbook/AddBankbookPresenter.jsx
  src/components/common/modals/AddSchedule.jsx
  src/components/common/modals/AddSchedule/AddScheduleContainer.jsx
  src/components/common/modals/AddSchedule/AddSchedulePresenter.jsx
Labels: fix

#43 update: 예산 계획 페이지 버튼 제목 "등록" 기재
  src/components/units/budgetPlan/BudgetPlan.presenter.jsx
Labels: update

#49 update: EditableTable 행 선택 개선 및 넘칠 시 스크롤 추가, 행 개수 7개로 조정
  src/components/common/layout/table/editableTable/index.jsx
Labels: update

#53 update: 빈 테이블 표시에 테이블 높이에 맞지 않는 아이콘 위치 조정
  src/components/common/layout/table/editableTable/index.jsx
Labels: update

#55 feat: 조회조건 영역 숫자 범위 컴포넌트 추가 - rangeNumber
  src/components/common/layout/conditions/conditionPicker/index.jsx
  src/components/common/layout/conditions/conditionbar/index.jsx
  src/components/units/budgetPlan/BudgetPlan.container.jsx
Labels: feature

#57 feat: sidebar 접기 기능 추가 외 2건
  src/components/common/layout/sidebar/index.jsx
Labels: update

#59 feature: 공지사항 및 공지사항 상세 페이지 UI 구현
  pages/announcement/[id].jsx
  pages/announcement/index.jsx
  src/components/units/announcement/Announcement.container.jsx
  src/components/units/announcement/Announcement.presenter.jsx
  src/components/units/announcement/announcementDetail/AnnouncementDetail.container.jsx
  src/components/units/announcement/announcementDetail/AnnouncementDetail.presenter.jsx
  src/components/units/main/Main.container.jsx
Labels: feature
